### ISSUE TITLE
海报插件报错

### ISSUE THREAD

**Issue by Elfantasmal** [0377/yfcmf-tp6#5]
ErrorException in PosterLogic.php line 277

getimagesize(): Peer certificate CN=`*.eiseverywhere.com' did not match expected CN=`www.demo.com'

**Comment by Elfantasmal** [comment]
@0377 `
            //背景图
            $qrcode_bg = root_path().'public'.$poster['image'];//**这里改成绝对路径读取就不会报错了**
            //海报未知
            $path_1 = public_path('public');
            $path_2 = 'qrcodes/poster/'.$poster->id.'/'.$user_id;
            $path_3 = '/'.$user_id.'_'.$poster->id.'.jpg';
            $filename = $path_1.$path_2.$path_3;
            $filename2 = '/'.$path_2.$path_3;
            //检测用户海报是否存在
            if (file_exists($filename)) {
                //已存在
                $data[] = cdnurl($filename2, true);
                continue;
            }
`

**Comment by 0377** [comment]
已修复
